### ISSUE TITLE
It is not possible to define the parameters of the constructor as shown in the example.

### ISSUE THREAD

**Issue by matheusjohannaraujo** [HashLDash/Photon#107]
```python

class Person():

    def new(str .name, int .age, str .gen = "-1"):

    def print_name():
        print("My name is {.name}")

    def print_age():
        print("My age is {.age} years old")

    def print_gen():
        if .gen == "1" or .gen == "Man":
            .gen = "Man"
        elif .gen == "0" or .gen == "Woman":
            .gen = "Woman"
        else:
            .gen = "Undefined"
        print("I am a {.gen}")

person = Person("Matheus", 23, "1")
person.print_name()
person.print_age()
person.print_gen()

print()

person = Person(age=30, name="William")
person.print_name()
person.print_age()
person.print_gen()

```

```python

C:\Users\windows\Desktop\Photon\examples>photon class.w
Traceback (most recent call last):
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 168, in run
    struct, nextLine = self.handleTokenized(tokenized)
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 152, in handleTokenized
    struct = self.handleBlock(tokenized)
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 135, in handleBlock
    block, nextTokenized = self.getBlock(indent)
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 112, in getBlock
    struct, nextLine = self.handleTokenized(blockTokenized)
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 152, in handleTokenized
    struct = self.handleBlock(tokenized)
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 145, in handleBlock
    struct = assembly(tokenized)
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 176, in assembly
    reduced = reduceToken(tokens)
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 139, in reduceToken
    reducedTokens = reduce()
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 128, in reduce
    result = reduceToken(patterns[pattern](i+1,tokens))
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 147, in reduceToken
    showError(f'SyntaxError')
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 195, in showError
    raise SyntaxError(msg)
SyntaxError:


    Ops!! This is a syntax error or a parser error.
    Common causes: Missing "," ")" "}"
    SyntaxError
    This happened in line class.w:6.
    Last parsed line is "

        def print_name():

"
    Last Parse attempt was:
 "defStatement expr ( type expr , type expr , type assign ) :"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\Desktop\Photon\core\photon.py", line 120, in <module>
    Interpreter(filename = first, lang = lang, standardLibs = os.path.join(PHOTON_INSTALL_PATH, 'libs/'), debug = DEBUG).run()
  File "C:\Users\windows\Desktop\Photon\core\interpreter.py", line 170, in run
    showError(e)
  File "C:\Users\windows\Desktop\Photon\core\photonParser.py", line 195, in showError
    raise SyntaxError(msg)
SyntaxError:


    Ops!! This is a syntax error or a parser error.
    Common causes: Missing "," ")" "}"



    Ops!! This is a syntax error or a parser error.
    Common causes: Missing "," ")" "}"
    SyntaxError
    This happened in line class.w:6.
    Last parsed line is "

        def print_name():

"
    Last Parse attempt was:
 "defStatement expr ( type expr , type expr , type assign ) :"

    This happened in line class.w:6.
    Last parsed line is "

        def print_name():

"
    Last Parse attempt was:
 "defStatement expr ( type expr , type expr , type assign ) :"

```

**Comment by HashLDash** [comment]
implemented by commit 1a0930c
