### ISSUE TITLE
Erro Infering type \n {'value': 'type(a)', 'type': 'unknown'}

### ISSUE THREAD

**Issue by Samuel-Nonato** [HashLDash/Photon#135]
Frist i change the compiler language from py to C

```
> PS C:\Users\Usuario\Desktop> photon -l c                                                                                
> Setting default lang to: C
> Some dependencies must be installed for this target language.
> # PowerShell is installed!
> # Chocolatey is installed!
> # Installing dependency with Chocolatey - Command:
> 
> powershell -Command "Start-Process powershell -Verb RunAs -PassThru -Wait -ArgumentList \"/c choco install mingw; timeout /t 5; exit\""
> 
> # Result:
> 
> Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
> -------  ------    -----      -----     ------     --  -- -----------
>      18       4      428       2032       0,02   4344   6 powershell
> Dependencies successfuly installed.
```

After i tryed to execult my simple test code but that time i increaced the c in output space

```
> PS C:\Users\Usuario\Desktop> photon test.w[enter]                                                                              
> Infering type
> {'value': 'type(a)', 'type': 'unknown'}c[enter]
> Infering type
> {'value': 'type(a)', 'type': 'unknown'}c[enter]
> Traceback (most recent call last):
>   File "C:\Photon-main\core\photon.py", line 127, in <module>
>     Interpreter(filename = first, lang = lang, standardLibs = os.path.join(PHOTON_INSTALL_PATH, 'libs/'), debug = DEBUG).run()
>   File "C:\Photon-main\core\interpreter.py", line 173, in run
>     self.engine.process(struct)
>   File "C:\Photon-main\core\transpilers\baseTranspiler.py", line 86, in process
>     self.instructions[token['opcode']](token)
>   File "C:\Photon-main\core\transpilers\baseTranspiler.py", line 498, in processAssign
>     self.insertCode(self.formatAssign(variableName, varType, cast, expr, inMemory=inMemory))
>   File "C:\Photon-main\core\transpilers\cTranspiler.py", line 390, in formatAssign
>     varType = self.nativeType(varType) + ' '
>   File "C:\Photon-main\core\transpilers\baseTranspiler.py", line 94, in nativeType
>     raise NotImplemented
> TypeError: exceptions must derive from BaseException
```
    But before i hasn't acreaced nothing

```

> PS C:\Users\Usuario\Desktop> photon .\test.w [enter]
>  Infering type
> {'value': 'type(a)', 'type': 'unknown'} [enter]
> Infering type
> {'value': 'type(a)', 'type': 'unknown'}[enter]
> 9 #real result
> <class 'int'> #rial result

```

This erro happen for that code

int a = 9.5
print(a)
b = type(a)
print(b)
~
~
~      
PS: Sorry my english if i has something erro of grammar or sintax.
PS: I love the idea of the a programmer language like photon, please fix it.

**Comment by Huyston** [comment]
Hey, welcome to the Photon community!!
The error is because the function "type" is not a Photon function. It is only valid in a Python environment. This is why it only works in the Python target.

I'll write in portuguese now:
Seja bem vindo!
O problema é que você está usando a função "type" que só é válida no target Python, pois ela não é uma função padrão do Photon. Você também pode tirar dúvidas pelo nosso canal do Discord.

**Comment by Samuel-Nonato** [comment]
OK, thank you, but exist a tutorial or a dictionary that i can use?

**Comment by Huyston** [comment]
We do have tutorials online on my english channel HashLDash english, some lives in my portuguese channel HashLDash and some example code in this repository. We also have a discord channel to help users and mentor developers that want to help.

**Comment by HashLDash** [comment]
Closing this because it's not a Photon bug.
